# Generated by Django 2.2.2 on 2019-06-23 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=100, verbose_name='收件地址')),
                ('signer_name', models.CharField(default='', max_length=20, verbose_name='收件人姓名')),
                ('signer_phone', models.CharField(default='', max_length=11, verbose_name='收件人电话')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 6, 23, 20, 59, 32, 135634), verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '收件地址',
                'verbose_name_plural': '收件地址',
            },
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(choices=[(1, '好评'), (2, '中评'), (3, '差评')], default=1, max_length=50, verbose_name='啥评')),
                ('message', models.TextField(default='系统默认好评', help_text='评论内容', verbose_name='评论内容')),
                ('file', models.FileField(help_text='上传的文件', upload_to='', verbose_name='上传的文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 6, 23, 20, 59, 32, 135634), verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户品论',
                'verbose_name_plural': '用户品论',
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 6, 23, 20, 59, 32, 134636), verbose_name='添加时间')),
                ('goods', models.ForeignKey(on_delete=True, to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
    ]
