# Generated by Django 2.2.2 on 2019-06-26 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20190623_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 11, 41, 4, 366930), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 11, 41, 4, 365910), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 11, 41, 4, 365910), verbose_name='添加时间'),
        ),
    ]
