# Generated by Django 2.2.2 on 2019-06-26 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20190626_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 16, 54, 22, 39803), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 16, 54, 22, 38804), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='file',
            field=models.FileField(default='', help_text='上传的文件', upload_to='', verbose_name='上传的文件'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 16, 54, 22, 37805), verbose_name='添加时间'),
        ),
    ]
