# Generated by Django 2.2.2 on 2019-07-01 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_auto_20190626_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 17, 0, 34, 642406), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 17, 0, 34, 642406), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 17, 0, 34, 641403), verbose_name='添加时间'),
        ),
    ]
