# Generated by Django 2.2.2 on 2019-06-23 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_nums', models.IntegerField(default=0, verbose_name='商品数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 6, 23, 20, 59, 32, 140632), verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=50, verbose_name='订单编号')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='支付编号')),
                ('pay_status', models.CharField(choices=[('success', '支付成功'), ('cancel', '待支付')], max_length=10, verbose_name='支付状态')),
                ('is_pay', models.BooleanField(default=False, verbose_name='是否支付')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='订单总金额')),
                ('pay_time', models.DateTimeField(default=True, null=True, verbose_name='支付时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 6, 23, 20, 59, 32, 139633), verbose_name='添加时间')),
                ('address', models.CharField(default='', max_length=100, verbose_name='收件地址')),
                ('signer_name', models.CharField(max_length=20, verbose_name='收件人姓名')),
                ('signer_phone', models.CharField(max_length=11, verbose_name='收件人电话')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_nums', models.IntegerField(default=1, verbose_name='购物车数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 6, 23, 20, 59, 32, 139633), verbose_name='添加时间')),
                ('goods', models.ForeignKey(on_delete=True, to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
    ]
