# Generated by Django 2.2.2 on 2019-06-23 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='odergoods',
            name='goods',
            field=models.ForeignKey(on_delete=True, to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='odergoods',
            name='order',
            field=models.ForeignKey(on_delete=True, to='trade.OrderInfo', verbose_name='订单信息'),
        ),
    ]
