# Generated by Django 2.2.2 on 2019-06-25 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190625_1933'),
        ('trade', '0002_auto_20190623_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_nums', models.IntegerField(default=0, verbose_name='商品数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 6, 25, 19, 33, 38, 26013), verbose_name='添加时间')),
                ('goods', models.ForeignKey(on_delete=True, to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 25, 19, 33, 38, 26013), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 25, 19, 33, 38, 25013), verbose_name='添加时间'),
        ),
        migrations.DeleteModel(
            name='OderGoods',
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=True, to='trade.OrderInfo', verbose_name='订单信息'),
        ),
    ]
