# Generated by Django 2.2.2 on 2019-07-01 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_auto_20190701_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 17, 3, 22, 996236), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='支付时间'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 17, 3, 22, 994237), verbose_name='添加时间'),
        ),
    ]
