# Generated by Django 2.2.2 on 2019-07-01 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0015_auto_20190701_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 17, 5, 25, 695928), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='add_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('success', '支付成功'), ('cancel', '待支付')], default='cancel', max_length=10, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 17, 5, 25, 694929), verbose_name='添加时间'),
        ),
    ]
