# Generated by Django 2.2.2 on 2019-07-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0017_auto_20190701_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='add_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='add_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='添加时间'),
        ),
    ]
