# Generated by Django 2.2.2 on 2019-06-23 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_sn', models.CharField(default='', max_length=50, unique=True, verbose_name='商品的唯一编号')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('click_num', models.IntegerField(default=0, verbose_name='商品点击数')),
                ('sold_num', models.IntegerField(default=0, verbose_name='商品销量')),
                ('goods_num', models.IntegerField(default=0, verbose_name='商品库存数量')),
                ('price', models.FloatField(default=0, verbose_name='商品价格')),
                ('goods_intro', models.TextField(default='', verbose_name='商品简介')),
                ('ship_free', models.BooleanField(default=False, verbose_name='是否包邮')),
                ('goods_front_img', models.ImageField(blank=True, null=True, upload_to='good/images/', verbose_name='展示图片')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否新品')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 6, 23, 20, 59, 32, 130637), verbose_name='添加事件')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 6, 23, 20, 59, 32, 130637))),
                ('goods', models.ForeignKey(on_delete=True, related_name='images', to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品详情图',
                'verbose_name_plural': '商品详情图',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('category_type', models.CharField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], help_text='类别级别', max_length=50, verbose_name='类别级别')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航栏', verbose_name='是否导航栏')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 6, 23, 20, 59, 32, 129638), verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父类目级别', null=True, on_delete=True, related_name='sub_cat', to='goods.GoodsCategory', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='轮播图片')),
                ('index', models.IntegerField(default=0, verbose_name='轮播索引')),
                ('goods', models.ForeignKey(on_delete=True, to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '轮播商品',
                'verbose_name_plural': '轮播商品',
            },
        ),
    ]
