# Generated by Django 2.2.2 on 2019-06-25 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 25, 19, 33, 38, 16019), verbose_name='添加事件'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_front_img',
            field=models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='展示图片'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 25, 19, 33, 38, 15018), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 25, 19, 33, 38, 17018)),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='图片'),
        ),
    ]
