# Generated by Django 2.2.2 on 2019-07-01 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190701_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 19, 48, 31, 550385), verbose_name='添加事件'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 19, 48, 31, 549384), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 19, 48, 31, 551384)),
        ),
    ]
