# Generated by Django 2.2.2 on 2019-06-26 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190625_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 11, 41, 4, 358934), verbose_name='添加时间'),
        ),
    ]
